development:
  adapter: postgresql
  encoding: unicode
  database: lunch_app_development
  pool: 5
  host: localhost
  username: lunch_app
  

test:
  adapter: postgresql
  encoding: unicode
  database: lunch_app_test
  pool: 5
  host: localhost
  username: lunch_app
  