development:
  adapter: postgresql
  encoding: unicode
  database: lunch_app_development
  pool: 5
  username: taras
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: Lunch_app_test
  pool: 5
  username: taras
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>